### ISSUE TITLE
Feature Request: Add other commonly used XR packages: Monado-Vulkan-Layers, Wivrn, Motoc, and Oscavmgr

### ISSUE THREAD

**Issue by Nyxerproject** [nix-community/nixpkgs-xr#205]
Many xr packages are not in nixpkgs. Some are in a pr ([Wivrn](https://github.com/NixOS/nixpkgs/pull/316975/commits/97bdae453794f49fe7b77b946409c38c5f769a20), [monado-vulkan-layers](https://github.com/NixOS/nixpkgs/pull/301044/commits/45feaff766cb56f038c0656353863a8d153e5e3e)), while others are not packaged at all (Motoc, Oscavmgr).
Is it possible to add these packages to nixpkgs-xr and any other unpackaged LVRA program to nixpkgs-xr at some point? Thanks

**Comment by Scrumplex** [comment]
Currently in the process of packaging [oscavmgr](https://github.com/NixOS/nixpkgs/pull/339627) and [VrcAdvert](https://github.com/NixOS/nixpkgs/pull/339630)

**Comment by Pandapip1** [comment]
I've made a PR for motoc: https://github.com/NixOS/nixpkgs/pull/340172
